version: "3.8"

services:

  app:
    image: webdevops/php-apache-dev:7.4
    volumes:
      - $PWD:/app
    ports:
      - 8000:8000
    environment:
      - WEB_DOCUMENT_ROOT=app/public 

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=qwerty
