version: "3"

services:

  app:
    build: .
    depends_on:
      - composer
      - db
    volumes:
      - $PWD:/app
    ports:
      - 8000:8000
    environment:
      - WEB_DOCUMENT_ROOT=app/public

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=qwerty
  qbit:
    image: linuxserver/qbittorrent
    restart: unless-stopped
    volumes:
    - $PWD/public/files:/downloads
    - $PWD/../qbitconfig:/config
    ports:
    - 6881:6881/udp
    - 8888:8888
    environment:
      - PUID=1000
      - PUIG=1000
      - TZ=Europe/Moscow
      - UMASK_SET=022
      - WEBUI_PORT=8888
  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
    - $PWD:/app
