version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfiles/app/Dockerfile
    depends_on:
      - composer
      - db
    ports:
      - 8000:80
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - videovolume:/app/public/files

  db:
    container_name: db
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=qwerty
    volumes:
    - dbvolume:/var/lib/mysql

  qbit:
    container_name: qbit
    image: linuxserver/qbittorrent
    restart: unless-stopped
    volumes:
    - videovolume:/downloads
    - $PWD/../qbitconfig:/config
    ports:
    - 6881:6881/udp
    - 8888:8888
    environment:
      - PUID=1
      - PUIG=1
      - TZ=Europe/Moscow
      - UMASK_SET=022
      - WEBUI_PORT=8888

  migrator:
    build:
      context: .
      dockerfile: Dockerfiles/migrator/Dockerfile
    restart: 'no'
    depends_on:
      - db
      - composer

  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
    - $PWD:/app

volumes:
  dbvolume:
  videovolume:
